Add a handler for empty string logs
crane-cloud/backend pull request #180
Opened 2020-11-23 09:58 UTC by Mubangizi

#### What this PR does
- Returns `No logs message` for apps with empty strings

2020-11-23 10:19 UTC, MutegekiHenry approved these changes

2020-11-24 07:40 UTC, neelxie approved these changes
Thanks @Mubangizi

2020-11-25 13:51 UTC, inno-asiimwe commented on app/controllers/app.py
> +        if pods_logs == [] or len(pods_logs[0]) == 0:
```suggestion
        if not pods_logs or not pods_logs[0]:
```

2020-11-25 13:52 UTC, inno-asiimwe requested changes
@Mubangizi we can make the change more pythonic

2020-11-25 15:08 UTC, inno-asiimwe approved these changes
LGTM

2020-11-26 08:26 UTC, merged