Adding pagination to some GET endpoints
crane-cloud/backend pull request #393
Opened 2023-02-25 07:41 UTC by LanternNassi

# Description

Adding pagination to relevant critical GET endpoints 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/EL7nv3ce/1375-add-pagination-to-most-endpoints

## How Can This Be Tested?

This can be tested by adding page and per_page values as query parameters with their respective values to the modified GET endpoint URL

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-03-01 10:27 UTC, Mubangizi requested changes
Hey @LanternNassi, Great work on this. 
Just a quick suggestion for you to put `Pagination` before the `items` list data, such that when anyone is reading through the data, they don't have to scroll at the bottom of the list to see the pagination info

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/users.py
> +            data=dict(users=json.loads(users_data) , pagination=users.pagination)
```suggestion
            data=dict(pagination=users.pagination, users=json.loads(users_data))
```

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/transactions.py
> +            transaction=json.loads(transaction_data), pagination=transaction.pagination)), 200
```suggestion
           pagination=transaction.pagination, transaction=json.loads(transaction_data))), 200
```

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/receipts.py
> +            billing_receipts=json.loads(billing_receipts_data) , pagination=billing_receipts.pagination)), 200
Same here
```suggestion
            pagination=billing_receipts.pagination, billing_receipts=json.loads(billing_receipts_data))), 200
```

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/project_database.py
> +        return dict(status='success', data=dict(databases=database_data_list, pagination=pagination)), 200
```suggestion
        return dict(status='success', pagination=pagination, data=dict(databases=database_data_list)), 200
```

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/project_database.py
> +        return dict(status='success', data=dict(databases=database_data_list, pagination=pagination)), 200
```suggestion
        return dict(status='success', pagination=pagination, data=dict(databases=database_data_list)), 200
```

2023-03-01 10:27 UTC, Mubangizi commented on app/controllers/billing_invoice.py
> +            billing_invoice=json.loads(billing_invoice_data), pagination=billing_invoice.pagination)), 200
```suggestion
pagination=billing_invoice.pagination, billing_invoice=json.loads(billing_invoice_data))), 200
```

2023-03-02 14:40 UTC, Mubangizi approved these changes
LGTM

2023-03-03 05:48 UTC, MutegekiHenry approved these changes
LGTM

2023-03-06 06:26 UTC, merged