feat: Add support for viewing inactive users per specific date.
crane-cloud/backend pull request #418
Opened 2023-06-06 19:31 UTC by jnsereko

# Description
Since logic for supporting last-seen is already in existed, inactive users is built on top of it in a way that if a user has. not logged in to the platform since the specified date, they will be added to a list of inactive users and then returned.

The logic caches results per date so that the next time the same date is entered, the saved cache is returned.

with bigger databases, if this slow we shall spawn a background thread to recompute for new dates there by reducing lots of execution time

cc @MutegekiHenry @neelxie

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

Please add a link to the Trello ticket for the task.

## How Can This Be Tested?

Pull down the changes 
- `git cherry-pick`
- run the server
- execute `http://127.0.0.1:5000/users/inactive_users?date=2000-12-05` using postman

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-08 10:06 UTC, MutegekiHenry requested changes
Great work @jnsereko 👏🏻 Maybe one aspect you missed was computing how many days/weeks/months from entered date to that of last logged in so that we base off that to filter and only send emails to those who have not logged in as per a certain creteria.

2023-06-12 21:16 UTC, jnsereko commented
hey @MutegekiHenry, could this be the required implementation?

2023-06-16 07:07 UTC, LanternNassi commented on app/controllers/users.py
> +            }
```suggestion
            pagination , users_data = paginate(self.computed_results,per_page,page)
```
We have a helper function for pagination under the helper functions that we can reuse in such cases of manual pagination . It helps keep the code more precise, easy to read and maintainable.
Import it from `from app.helpers.pagination import paginate`

2023-06-22 13:37 UTC, MutegekiHenry approved these changes
LGTM

2023-06-22 18:23 UTC, merged