Improved Email templates
crane-cloud/backend pull request #485
Opened 2024-02-28 13:23 UTC by KiraboIsaacBuyondo

# Description

- This PR aims to improve the anonymous_user_to_project email using the standard emailing template created in Figma. It takes care of the standard branding, sizes, font styles, general layout, and background formats.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

1. https://trello.com/c/IWyB6AVy  
2. https://trello.com/c/IQqVNWgZ

## How Can This Be Tested?

- Run the branch on your local machine. 
- Send an invitation email to an anonymous user.
- Check its appearance on various devices for font size, colors, etc.
- Test the social media icons for Medium, LinkedIn, YouTube, and X to ensure they link to the official Crane Cloud social media platforms.

## Screenshot
![Crane Cloud](https://github.com/crane-cloud/backend/assets/87686674/203e8c17-f6f5-4a1d-97e6-a96cebca3170)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-29 10:37 UTC, Mubangizi requested changes
Great work Kirabo, just a little feedback.
1. Please put all the content in the white box, ie the greeting and the contact information. Also work on making the contact info ie footer areas font slightly smaller than the general body font. this is in accordance to the image of the email shared
2. Remove the **icons** folder and its files, then use a library ie `font Awesome` to add the socials icons. something like

> ```
><!-- Add icon library -->
><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font->awesome/4.7.0/css/font-awesome.min.css">
>
><!-- Add font awesome icons -->
><a href="#" class="fa fa-facebook"></a>
><a href="#" class="fa fa-twitter"></a>
>```

2024-02-29 10:37 UTC, Mubangizi commented on templates/user/anonymous_user_to_project.html
> -              {% if success ==true %}
As you can see `success` is for inviting users for collaboration, meaning you will break this workflow if you just eliminate it

2024-02-29 10:37 UTC, Mubangizi commented on templates/user/user_to_project.html
> -              {% if success ==true %}
You can also see `success` is used for informing users what they have been assigned as in a project

2024-03-02 07:43 UTC, Mubangizi approved these changes
LGTM

2024-03-02 12:51 UTC, rhodinemma approved these changes
Good work on this @KiraboIsaacBuyondo

2024-03-04 23:16 UTC, merged