Adding the pin feature
crane-cloud/backend pull request #503
Opened 2024-06-11 15:15 UTC by LanternNassi

# Description

This PR is meant to add the pinning feature to the project structure . A maximum of 6 projects can be pinned per user account.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/kAQsiG1k/1974-return-user-projects

## How Can This Be Tested?

Can be tested by hitting the `/projects/{project_id}/pin` to pin a project 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-12 09:38 UTC, Mubangizi requested changes
Hey @LanternNassi, great stuff. But I think we might need to rethink applying `pinned` directly on the `Project` model.

This is because we have **project collaboration**, meaning if 2 accounts are collaborating a one project, if one account pins the project, it will also show up on the other accounts pinned projects.

I suggest you add `pinned` to the `ProjectUser` model, so If I pin a project it is attached to my user_id, and I pick pinned projects from the `ProjectUser` table

2024-06-12 09:38 UTC, Mubangizi commented on app/controllers/project.py
> +                message = 'Pinned projects cant more than 6'
```suggestion
                message = 'Pinned projects cant be more than 6'
```

2024-06-12 09:38 UTC, Mubangizi commented on app/controllers/project.py
> +        user = User.get_by_id(current_user_id)
These checks may not be necessary, please use the existing logic we have been using for validation
```suggestion
       if not project:
            return dict(
                status='fail',
                message=f'project {project_id} not found'
            ), 404

        if not is_owner_or_admin(project, current_user_id, current_user_roles):
            if not is_authorised_project_user(project, current_user_id, 'member'):
                return dict(status='fail', message='unauthorised'), 403
        
        if (project.pinned):
            return dict(
                status = 'fail',
                message = 'The project was already pinned'
            ),409
```

2024-06-12 09:38 UTC, Mubangizi commented on app/controllers/project.py
> +        pinned_projects = [project for project in user.projects if (project.pinned != 'null' or project.pinned )]
Getting an entire users list of projects and looping through it might be costly. Rather do a query against the database
```suggestion
        pinned_projects_count = Project.count(Project.owner_id = current_user_id, pinned=True)
```

2024-06-12 10:32 UTC, LanternNassi commented on app/controllers/project.py
> +                message = 'Pinned projects cant more than 6'
Thanks for this

2024-06-17 09:03 UTC, Mubangizi commented on app/controllers/project.py
> +                message = 'Pinned projects cant more than 6'
You still dint change it

2024-06-17 09:08 UTC, Mubangizi commented on app/controllers/project.py
> +        if (not project_user):
Like I highlighted before, please use existing project access logic, otherwise we will be forced to come back and modify this very line if we were to refactor the logic in the entire application
```suggestion
      if not is_authorised_project_user(project, current_user_id, 'member'):
                return dict(status='fail', message='unauthorised'), 403
```

2024-06-17 09:08 UTC, Mubangizi commented on app/controllers/project.py
> +        if (not project_user):
Use the same project access logic here too

2024-06-17 20:05 UTC, Mubangizi requested changes

2024-06-17 20:05 UTC, Mubangizi commented on app/routes/__init__.py
> +api.add_resource(ProjectPinView, '/projects/<string:project_id>/pin')
You dint import `ProjectPinView` and tests are failing because of it

2024-06-19 06:08 UTC, Mubangizi approved these changes

2024-06-19 06:10 UTC, merged