User profile Visibility
crane-cloud/backend pull request #504
Opened 2024-06-11 18:01 UTC by LanternNassi

# Description

This feature is to add user visibility (true or false)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

https://trello.com/c/jdG2RFOk/1965-making-users-profiles-private-or-public

## How Can This Be Tested?

This can be tested by patching user's information through `/users/{user_id}` with the field `public : true or false` . This makes the user profile public or private.  

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-12 10:00 UTC, Mubangizi requested changes

2024-06-12 10:00 UTC, Mubangizi commented on app/controllers/project.py
> +class ProjectPinView(Resource):
Hey @LanternNassi I think **Pinning** logic is a different feature in a different PR. 
You were supposed to branch off the base branch for this, not the pin logic branch. 

The Pinning logic is still being updated so having it in here will cause inconsistencies and break things, so please remove it

2024-06-12 10:00 UTC, Mubangizi commented on app/controllers/users.py
> +            user_schema = UserSchema()
We do this to limit fields that will be updated so when you open in up, it may cause issues long term
```suggestion
      user_schema = UserSchema(only=("name", "public"))
```

2024-06-12 10:00 UTC, Mubangizi commented on app/controllers/users.py
> +            validate_user_data, errors = user_schema.load({**user.__dict__,**dict(user_data)})
I think you only need to load the schema with data that has been sent from the request object 
```suggestion
            validate_user_data, errors = user_schema.load(user_data)
```

2024-06-12 10:00 UTC, Mubangizi commented on app/models/user.py
> +    public = db.Column(db.Boolean, default=False)
This is a small issue, just to improve readability. We had agreed you set the field to either `is_public` or `is_private` and also that accounts are supposed to be set public by default.

So understanding what this means having set `public` to a default of `False` might cause misinterpretation when working with this field

2024-06-12 11:05 UTC, LanternNassi commented on app/models/user.py
> +    public = db.Column(db.Boolean, default=False)
Thanks for this . I think it skipped me

2024-06-17 20:14 UTC, Mubangizi requested changes
I think you missed some areas when you were refactoring

2024-06-17 20:14 UTC, Mubangizi commented on app/controllers/users.py
> +            if (not user) :
This is repeated code your adding here, so please remove it
` return dict(
                    status = 'Not found',
                    message = f'User not with id {user_id} not found'
                ),404`
```suggestion
  
```

2024-06-17 20:14 UTC, Mubangizi commented on app/controllers/users.py
> +            user_schema = UserSchema(only=("name", "public"))
This should be
```suggestion
            user_schema = UserSchema(only=("name", "is_public"))
```

2024-06-17 20:14 UTC, Mubangizi commented on api_docs.yml
> +              public:
```suggestion
              is_public:
```

2024-06-18 08:52 UTC, Mubangizi approved these changes

2024-06-18 09:21 UTC, merged