Feat: enable user see a summary of user data
crane-cloud/backend pull request #512
Opened 2024-07-03 12:46 UTC by khalifan-kfan

# Description

Enable user see a summary of user data

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/i1kvPTlL

## How Can This Be Tested?

Run this branch and try to fetch any profiles's summary  on route 
http://localhost:50000/users/profile_summary/<id>

2024-07-03 13:11 UTC, LanternNassi submitted a review, later dismissed
LGTM

2024-07-03 13:11 UTC, LanternNassi commented on app/controllers/users.py
> +            print('hdf')
```suggestion
```

2024-07-03 13:11 UTC, LanternNassi commented on app/controllers/users.py
> +            print(user_data)
```suggestion
```

2024-07-04 07:14 UTC, Mubangizi requested changes
Hey @khalifan-kfan, Great work here. But I think we already have an endpoint for this and its under `GET` for `UserDetailView(Resource):`. So if you want to add more info just update what is returned on that route

2024-07-04 07:17 UTC, khalifan-kfan commented
Alright @Mubangizi  and @LanternNassi, thanks for the feedback, this is going to be worked on

2024-07-04 09:03 UTC, khalifan-kfan commented
@Mubangizi  and @LanternNassi  this has been resolved

2024-07-04 09:46 UTC, Mubangizi approved these changes

2024-07-04 09:57 UTC, merged