Refactor/upgrades dependencies and config test
crane-cloud/backend pull request #513
Opened 2024-07-04 07:46 UTC by Emmanuel-Dominic

# Description
This PR includes several important updates and optimizations to the project.
- Key changes include, rewritten and optimized test cases, updated import statements based on upgraded packages and usage, a cleaned-up requirements.txt with updated dependencies, modified Alembic migration files and configurations, a refactored "SoftDeleteQuery" model file for better performance, and the removal of unused imports to enhance code readability and execution speed. These updates aim to maintain a clean, maintainable, and efficient codebase while improving the performance and reliability of the application.

The motivation behind these changes is to:
- Ensure the codebase remains clean, maintainable, and efficient.
- Improve the performance and reliability of the application.
- Align the project with the latest standards and best practices.
- Facilitate future development and integration efforts.

## Type of change

- [x] Chore (maintenance task such as refactoring, updating dependencies, improving documentation, or other non-functional changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Trello Ticket ID
- NOT AVAILABLE

## How Can This Be Tested?
This can be tested by verifying the updates made in the files against the documentation for each used package and by following the steps required to set up and run the application as indicated in the readme.

- `@jwt_required` updated to `@jwt_required()`.
- `get_jwt_claims` updated to `get_jwt`.
- `user_claims_loader` updated to `additional_claims_loader`.
- Remove from `flask_sqlalchemy import Model` from `backend.app.models.transaction_records`.
- Rewrite `SoftDeleteQuery` class in the `bacend.app.models.model_mixin`.

## Screenshots
- Run Tests
![Screenshot from 2024-07-02 19-24-52](https://github.com/crane-cloud/backend/assets/50827537/312f24e5-7198-4da2-8d68-ffff10d2137f)

- Run Migrations
![Screenshot from 2024-07-02 19-40-45](https://github.com/crane-cloud/backend/assets/50827537/8f678b04-04d9-468b-a41e-9a0e400769f4)

- Run db upgrade
![Screenshot from 2024-07-02 19-41-20](https://github.com/crane-cloud/backend/assets/50827537/30cd8d28-b4b9-47fa-b7dc-690d92ef4d51)

- Database schema
![Screenshot from 2024-07-02 19-42-15](https://github.com/crane-cloud/backend/assets/50827537/8c0db443-3e13-4fcc-b936-5f994f550231)

2024-07-04 08:02 UTC, Emmanuel-Dominic commented
@Mubangizi, @rhodinemma and @khalifan-kfan:

- It would be better to consider Python 3.8 and newer for the application, since most upgraded packages are supported by Python 3.8 and newer.

I am waiting on your confirmation.

2024-07-04 08:12 UTC, Mubangizi requested changes
Great work @Emmanuel-Dominic. These are alot of changes and they touch critical parts of the system, we can't have them in the same PR. It is very dangerous.

 I don't think tasks in here are actually dependant on each other, so break down them into small micro tasks and push them independently. ie
- Adding tests cases.
- Upgrading requirements (These you may need to also have them in separate PRs for those requirements that need to refactor a lot in the code base ie jwt )
- Updating soft delete logic

2024-07-04 08:16 UTC, Mubangizi commented
> @Mubangizi, @rhodinemma and @khalifan-kfan:
> 
> * It would be better to consider Python 3.8 and newer for the application, since most upgraded packages are supported by Python 3.8 and newer. [example](https://pyreadiness.org/3.6/)
> 
> NB: I am waiting on your confirmation.

This is fine, great catch

2024-07-04 08:24 UTC, Emmanuel-Dominic commented
> Great work @Emmanuel-Dominic. These are alot of changes and they touch critical parts of the system, we can't have them in the same PR. It is very dangerous.
> 
> I don't think tasks in here are actually dependant on each other, so break down them into small micro tasks and push them independently. ie
> 
> * Adding tests cases.
> * Upgrading requirements (These you may need to also have them in separate PRs for those requirements that need to refactor a lot in the code base ie jwt )
> * Updating soft delete logic

@Mubangizi, This approach is necessary because each package impacts the compatibility of the others and most changes focus on four major packages: Flask-JWT-Extended, SQLAlchemy, pytest, and Marshmallow.

NB: Therefore, I would recommend regression testing.

2024-07-04 08:34 UTC, Mubangizi commented
> regression testing.

These packages highlighted in here are still independent. Now for the sake of having a more focused and thorough review. please separate them. Like I said this is a big PR and it complicates things when a lot of switching contexts have to be reviewed and tested.

2024-07-04 08:36 UTC, Mubangizi commented
Maybe pull out the small things out and leave this to a single big module, then we start from there

2025-01-10 00:19 UTC, Mubangizi commented
Closing this for now

2025-01-10 00:19 UTC, closed without merging