allow Organisation update
crane-cloud/backend pull request #520
Opened 2024-07-17 12:13 UTC by CHRISTOPHERKADOGO

# Description

This PR Allows to update organization for users, and also make patch endpoint flexible to cater for updating individual properties about the user

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## ClickUp Ticket ID
https://app.clickup.com/t/869542h0p

## How Can This Be Tested?
Run this  branch  locally and try updating the properties about user (name, is public, organization)

2024-07-17 13:03 UTC, rhodinemma approved these changes
Thanks for this @CHRISTOPHERKADOGO

2024-07-17 13:03 UTC, rhodinemma commented on app/controllers/users.py
> +            user_schema = UserUpdateSchema()
Maybe instead of using a new schema, we could use the `Partial=true` on the existing schema.

2024-07-18 03:04 UTC, LanternNassi commented on app/controllers/users.py
> +            user_schema = UserSchema(partial=True)
Thanks for this Chris . Though this poses some security concerns on the endpoint as this means someone can modify fields such as `is_beta_user` , `verified `  once they can bundle them with the payload which are only to be updated under certain circumstances . 

```suggestion
            user_schema = UserSchema(only=("name", "is_public" , "organisation"))
```

2024-07-18 03:05 UTC, LanternNassi requested changes
Great Work on this

2024-07-19 10:02 UTC, LanternNassi approved these changes
LGTM . Nice work ..

2024-07-19 10:04 UTC, merged